server {
    listen 443 ssl http2;
    server_name admin.tilesclash.com;
    root /var/www/tilesclash/AdminPanel/public;

    ssl_certificate     /etc/letsencrypt/live/admin.tilesclash.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.tilesclash.com/privkey.pem;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
