server {
    listen 443 ssl http2;
    server_name admin.matchiq.com;

    ssl_certificate     /etc/letsencrypt/live/admin.matchiq.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/admin.matchiq.com/privkey.pem;

    root /var/www/matchiq/AdminPanel/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }
}
