server {
    listen 443 ssl http2;
    server_name matchiq.fun www.matchiq.fun www1.matchiq.fun;

    ssl_certificate     /etc/nginx/ssl-certificates/matchiq.fun.crt;
    ssl_certificate_key /etc/nginx/ssl-certificates/matchiq.fun.key;

    root /var/www/UnityTiles/Deployment/public;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name matchiq.fun www.matchiq.fun www1.matchiq.fun;
    return 301 https://matchiq.fun$request_uri;
}
